import type { JourneyData } from "./models";
const at = (days:number) => new Date(Date.now()-days*864e5).toISOString();
export const demo: JourneyData = { schema:"codex-journey/v1", generatedAt:new Date().toISOString(), projects:[
  {id:"flow-desk",name:"Flow Desk",area:"Trading systems",status:"deployed",summary:"Daily recap shipped once; recurring delivery remains deliberately disabled.",next:"Decide whether to authorize a bounded scheduler trial",updatedAt:at(1),score:{impact:5,urgency:4,unlock:5,staleness:1,risk:4,effort:2},blocker:"Recurring activation needs your approval",gate:"FLOW_RECAP_DELIVERY_ENABLED is off",milestones:["Implementation merged","One-time delivery verified"],decisions:["Keep production model unchanged"],evidence:[{id:"f1",type:"github",label:"Merged PR #109",href:"https://github.com",at:at(2),confidence:1},{id:"f2",type:"ops",label:"Deployment verified; scheduler disabled",at:at(1),confidence:1}]},
  {id:"course",name:"Agentic Trading Course",area:"Education",status:"in progress",summary:"Beginner course concept and partner narrative are taking shape.",next:"Lock the first four lesson outcomes",updatedAt:at(3),score:{impact:5,urgency:3,unlock:4,staleness:2,risk:1,effort:3},milestones:["Partner draft prepared"],evidence:[{id:"c1",type:"codex",label:"Course strategy thread",at:at(3),confidence:.8}]},
  {id:"trade-tracker",name:"Trade Tracker",area:"Trading systems",status:"verified",summary:"Runtime recovered and Discord catch-up observed after restart.",next:"Monitor normal unattended behavior",updatedAt:at(0),score:{impact:4,urgency:1,unlock:1,staleness:0,risk:2,effort:1},milestones:["Runtime healthy","Catch-up verified"],evidence:[{id:"t1",type:"git",label:"Runtime clone checked",at:at(0),confidence:.95},{id:"t2",type:"ops",label:"Discord connection verified",at:at(0),confidence:1}]},
  {id:"mac-travel",name:"Travel-ready Mac",area:"Personal operations",status:"waiting",summary:"Relay and local listener work; outside-network proof is still missing.",next:"Test SSH from the MacBook on a separate network",updatedAt:at(18),score:{impact:4,urgency:5,unlock:4,staleness:5,risk:2,effort:2},blocker:"Waiting on a physical outside-network test",milestones:["Relay paired","Tailscale configured"],evidence:[{id:"m1",type:"ops",label:"Local listener healthy",at:at(18),confidence:.9}]},
  {id:"fluence-docs",name:"Fluence Documents",area:"Business operations",status:"implemented",summary:"Core company documents are drafted with counsel-safe blanks.",next:"Review unresolved entity details before external filing",updatedAt:at(9),score:{impact:3,urgency:3,unlock:3,staleness:3,risk:3,effort:2},gate:"Verified entity details required",milestones:["Draft package complete"],evidence:[{id:"d1",type:"codex",label:"Document artifact generated",at:at(9),confidence:.85}]}
], ideas:[{id:"i1",title:"Turn production evidence into reusable release cards",rationale:"The same proof model can prevent ambiguity across every deployed tool.",relatedProject:"flow-desk",score:8.7},{id:"i2",title:"Record a five-minute course pilot",rationale:"A tiny audience test may resolve curriculum questions faster than more planning.",relatedProject:"course",score:8.1}]};
