import "./style.css";
import { applyCorrections, conflicts, exportMarkdown, rank, score, scoreExplanation, stale } from "./core";
import { demo } from "./fixtures";
import type { Correction, JourneyData, Project, Status } from "./models";

type View = "Today"|"Journey"|"Projects"|"Completed"|"Waiting on Me"|"Ideas"|"Evidence";
const views: View[] = ["Today","Journey","Projects","Completed","Waiting on Me","Ideas","Evidence"];
let data: JourneyData = demo; let view: View = "Today";
const saved = localStorage.getItem("codex-journey-corrections/v1");
const corrections: Correction[] = saved ? JSON.parse(saved) : [];
const root = document.querySelector<HTMLDivElement>("#app")!;

function esc(value:string):string { const el=document.createElement("span"); el.textContent=value; return el.innerHTML; }
function badge(p:Project):string { return `<span class="status status-${p.status.replace(/ /g,"-")}"><i></i>${esc(p.status)}</span>`; }
function evidence(p:Project):string { return `<div class="evidence">${p.evidence.slice(0,2).map(e=>`<${e.href?`a href="${e.href}" target="_blank" rel="noreferrer"`:"span"} class="evidence-chip"><b>${e.type}</b> ${esc(e.label)} · ${Math.round(e.confidence*100)}%</${e.href?"a":"span"}>`).join("")}</div>`; }
function projectCard(p:Project, priority=false):string { const s=score(p.score); return `<article class="project-card ${priority?"priority":""}">
  <div class="project-top"><div><p class="eyebrow">${esc(p.area)}</p><h3>${esc(p.name)}</h3></div>${badge(p)}</div>
  <p class="summary">${esc(p.summary)}</p>${(p.blocker||p.gate)?`<div class="attention"><span>Needs you</span>${esc(p.blocker??p.gate??"")}</div>`:""}
  <div class="next"><span>Next move</span><strong>${esc(p.next)}</strong></div>
  ${priority?`<details><summary>Why this ranks ${s}</summary><p>${scoreExplanation(p.score)}</p></details>`:""}${evidence(p)}
  <footer><time>${new Date(p.updatedAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time>${stale(p)?'<span class="stale">Stale evidence</span>':""}${conflicts(p)?'<span class="conflict">Conflicting signals</span>':""}<button class="text-btn" data-correct="${p.id}">Correct</button></footer>
  </article>`; }
function today():string { const top=rank(data.projects).slice(0,3); const done=data.projects.filter(p=>["verified","activated","deployed","merged","implemented"].includes(p.status)); const waiting=data.projects.filter(p=>p.status==="waiting"||p.status==="blocked"||p.gate); return `<section class="hero"><div><p class="kicker">YOUR WORK, WITH RECEIPTS</p><h1>Here’s the signal<br/>inside the motion.</h1><p>${data.projects.filter(p=>!["verified","abandoned"].includes(p.status)).length} active efforts · ${waiting.length} need your attention · refreshed ${new Date(data.generatedAt).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</p></div><div class="hero-meter"><span>FOCUS INDEX</span><b>${Math.round(top.reduce((n,p)=>n+score(p.score),0)/top.length)}</b><small>Evidence-weighted</small></div></section>
  <section><div class="section-title"><div><p class="eyebrow">THE NEXT THREE</p><h2>Highest-leverage moves</h2></div><span>Ranked transparently</span></div><div class="priority-grid">${top.map(p=>projectCard(p,true)).join("")}</div></section>
  <section class="split"><div><div class="section-title"><div><p class="eyebrow">WAITING ON YOU</p><h2>Decisions, not busywork</h2></div></div><div class="stack">${waiting.map(p=>`<button class="waiting-row" data-project="${p.id}"><span>${esc(p.name)}</span><b>${esc(p.blocker??p.gate??"Review needed")}</b><i>→</i></button>`).join("")||empty("Nothing is waiting on you.")}</div></div><div class="completed-panel"><p class="eyebrow">RECENT PROOF</p><h2>${done.length} outcomes moved forward</h2>${done.slice(0,3).map(p=>`<div><span>✓</span><p><b>${esc(p.name)}</b><small>${esc(p.milestones.at(-1)??p.status)}</small></p></div>`).join("")}</div></section>
  <section class="idea-strip"><span>IDEA WORTH A LOOK</span><div><h2>${esc(data.ideas[0]?.title??"No new idea yet")}</h2><p>${esc(data.ideas[0]?.rationale??"")}</p></div><button data-nav="Ideas">Explore →</button></section>`; }
function empty(message:string):string { return `<div class="empty"><span>○</span><b>${esc(message)}</b><p>Import evidence or adjust the filters to build this view.</p></div>`; }
function collection(title:string, subtitle:string, items:Project[]):string { return `<header class="page-head"><p class="eyebrow">${esc(view.toUpperCase())}</p><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></header><div class="collection">${items.length?items.map(p=>projectCard(p)).join(""):empty("No projects here yet.")}</div>`; }
function journey():string { const ordered=[...data.projects].sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt)); return `<header class="page-head"><p class="eyebrow">JOURNEY</p><h1>Progress over activity.</h1><p>A time-ordered account of work, decisions, and proof.</p></header><div class="timeline">${ordered.map(p=>`<article><time>${new Date(p.updatedAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</time><i></i><div>${badge(p)}<h2>${esc(p.name)}</h2><p>${esc(p.summary)}</p>${evidence(p)}</div></article>`).join("")}</div>`; }
function ideas():string { return `<header class="page-head"><p class="eyebrow">IDEAS</p><h1>The edge of the map.</h1><p>Useful possibilities derived from current work—not commitments.</p></header><div class="ideas-grid">${data.ideas.map(i=>`<article><span>${i.score.toFixed(1)}</span><p class="eyebrow">ADVISORY</p><h2>${esc(i.title)}</h2><p>${esc(i.rationale)}</p><small>Related: ${esc(i.relatedProject??"Across projects")}</small></article>`).join("")}</div>`; }
function evidenceView():string { const rows=data.projects.flatMap(p=>p.evidence.map(e=>({...e,project:p.name}))).sort((a,b)=>b.at.localeCompare(a.at)); return `<header class="page-head"><p class="eyebrow">EVIDENCE</p><h1>Trust, then verify.</h1><p>Every conclusion stays attached to provenance and confidence.</p></header><div class="evidence-table" role="table"><div class="table-head" role="row"><span>Project</span><span>Evidence</span><span>Source</span><span>Confidence</span></div>${rows.map(r=>`<div role="row"><b>${esc(r.project)}</b><span>${esc(r.label)}</span><code>${r.type}</code><span>${Math.round(r.confidence*100)}%</span></div>`).join("")}</div>`; }
function render():void { data=applyCorrections(demo,corrections); let content=""; if(view==="Today")content=today(); else if(view==="Journey")content=journey(); else if(view==="Ideas")content=ideas(); else if(view==="Evidence")content=evidenceView(); else { const filters:Record<string,(p:Project)=>boolean>={Projects:()=>true,Completed:p=>["implemented","merged","deployed","activated","verified"].includes(p.status),"Waiting on Me":p=>p.status==="waiting"||p.status==="blocked"||!!p.gate}; content=collection(view==="Projects"?"Everything in motion.":view,view==="Projects"?"Grouped by evidence, not optimism.":"Clear outcomes and the proof behind them.",data.projects.filter(filters[view])); }
root.innerHTML=`<aside><div class="brand"><span>CJ</span><b>CODEX<br/>JOURNEY</b></div><nav aria-label="Primary">${views.map(v=>`<button class="${view===v?"active":""}" data-nav="${v}"><span>${icon(v)}</span>${v}</button>`).join("")}</nav><div class="aside-foot"><span class="pulse"></span><div><b>Local sources</b><small>Demo snapshot · private</small></div></div></aside><div class="shell"><header><button class="menu" aria-label="Open navigation">☰</button><div><span class="source-dot"></span>Evidence current</div><div class="actions"><button id="import">Import</button><button id="export" class="primary">Export context</button></div></header><main id="main">${content}</main></div><div id="modal"></div>`; bind(); }
function icon(v:View):string { return ({Today:"⌁",Journey:"↗",Projects:"▦",Completed:"✓","Waiting on Me":"!",Ideas:"✦",Evidence:"⌘"})[v]; }
function bind():void { document.querySelectorAll<HTMLElement>("[data-nav]").forEach(el=>el.onclick=()=>{view=el.dataset.nav as View;render()}); document.querySelector(".menu")?.addEventListener("click",()=>document.querySelector("aside")?.classList.toggle("open")); document.querySelectorAll<HTMLElement>("[data-correct]").forEach(el=>el.onclick=()=>openCorrection(el.dataset.correct!)); document.querySelector("#export")?.addEventListener("click",async()=>{await navigator.clipboard.writeText(exportMarkdown(data)); toast("Planning context copied")}); document.querySelector("#import")?.addEventListener("click",()=>importPicker()); }
function openCorrection(id:string):void { const p=data.projects.find(x=>x.id===id)!; const modal=document.querySelector("#modal")!; modal.innerHTML=`<div class="modal-back"><form class="modal"><button type="button" class="close" aria-label="Close">×</button><p class="eyebrow">YOUR CORRECTION WINS</p><h2>${esc(p.name)}</h2><label>Status<select name="status">${["started","in progress","waiting","blocked","implemented","merged","deployed","activated","verified","paused","abandoned"].map(s=>`<option ${s===p.status?"selected":""}>${s}</option>`).join("")}</select></label><label>Note<textarea name="note" placeholder="What should Codex Journey know?"></textarea></label><button class="primary" type="submit">Save correction</button></form></div>`; modal.querySelector(".close")?.addEventListener("click",()=>modal.innerHTML=""); modal.querySelector("form")?.addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.currentTarget as HTMLFormElement);corrections.push({projectId:id,status:f.get("status") as Status,note:String(f.get("note")??""),at:new Date().toISOString()});localStorage.setItem("codex-journey-corrections/v1",JSON.stringify(corrections));render();toast("Correction saved locally")}); }
function importPicker():void { const input=document.createElement("input");input.type="file";input.accept="application/json,.jsonl";input.onchange=async()=>{const file=input.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text()) as JourneyData;if(parsed.schema!=="codex-journey/v1")throw Error();demo.projects=parsed.projects;demo.ideas=parsed.ideas;demo.generatedAt=parsed.generatedAt;render();toast("Snapshot imported locally")}catch{toast("That file is not a Journey snapshot")}};input.click(); }
function toast(message:string):void { const el=document.createElement("div");el.className="toast";el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2600); }
render();
